---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
stringData:
  url: "mongodb://rootuser:root123@mongodb-service:27017/hr_system?authSource=admin"
  username: rootuser
  password: root123
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: thanu-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: password
 
 
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: thanu-ns
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recruitment-app
  namespace: thanu-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recruitment-app
  template:
    metadata:
      labels:
        app: recruitment-app
    spec:
      containers:
      - name: recruitment-app
        image: thanusri22/recruitment:v1.1.0
        ports:
        - containerPort: 3000
        env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: url
 
---
apiVersion: v1
kind: Service
metadata:
  name: recruitment-service
  namespace: thanu-ns
spec:
  selector:
    app: recruitment-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30085
  type: NodePort
 