events {}

http {

    upstream recruitment_service {
        server recruitment-app:5000;
    }

    server {
        listen 80;

        location /recruitment/ {
            proxy_pass http://recruitment_service;
        }

    }
}